### ISSUE TITLE
Search: using deprecated API (https://readthedocs.org/api/v2/docsearch/)

### ISSUE THREAD

**Issue by stsewd** [cakephp/docs-theme#2]
Hi! I work at Read the Docs, I'm reaching to you since we are in the process of removing this undocumented API (https://readthedocs.org/api/v2/docsearch). We are replacing it with https://docs.readthedocs.io/en/stable/server-side-search.html#api

I noticed you are using the old API at https://github.com/cakephp/docs-theme/blob/3e3c767e49d53fd51c91d3007e22ef6de36a5a1e/cakephp_theme/static/app.js#L869

You can check how we use the new api at https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/doc-embed/search.js and https://github.com/readthedocs/readthedocs-sphinx-search/blob/master/sphinx_search/static/js/rtd_sphinx_search.js

The old api will be removed soon

**Comment by markstory** [comment]
Closing this as I think we have this fixed, or it will be fixed as sites rebuild their docs.
